### PR TITLE
Add support for `holidays` 5.1.x

### PR DESCRIPTION
**Pull request by phlipper**
This PR adds support for `holidays` 5.1.x.

### CODE REVIEW

**Comment by phlipper** [comment]
@jm81 can you please release a new gem version with these updates? Thanks!

**Comment by jm81** [comment]
Yes, I will--I'm on vacation this week, so it may be as late as Sunday before I get it done.

**Comment by jm81** [comment]
I got a chance to release the updated gem this morning. Thanks for the PRs!

**Comment by phlipper** [comment]
@jm81 thank you very much! Enjoy your vacation!

**Pull request merged**
